services:

  accountapp.db:
    image: mcr.microsoft.com/mssql/server

  clientapp.db:
    image: mcr.microsoft.com/mssql/server

  database.init:
    image: mcr.microsoft.com/mssql/server

  rabbitmq:
    image: rabbitmq:management-alpine

  accountapp.api:
    image: ${DOCKER_REGISTRY-}accountappapi
    build:
      context: .
      dockerfile: AccountApp.Api/Dockerfile

  clientapp.api:
    image: ${DOCKER_REGISTRY-}clientappapi
    build:
      context: .
      dockerfile: ClientApp.Api/Dockerfile

volumes:
  data_accountapp: 
  data_clientapp:
