services:
  cuentaapi:
    image: ${DOCKER_REGISTRY-}cuentaapi
    build:
      context: .
      dockerfile: CuentaAPI/Dockerfile

  clienteapi:
    image: ${DOCKER_REGISTRY-}clienteapi
    build:
      context: .
      dockerfile: ClienteAPI/Dockerfile

