services:

  cuentadb:
    image: mcr.microsoft.com/mssql/server

  clientedb:
    image: mcr.microsoft.com/mssql/server

  cuentaapi:
    image: ${DOCKER_REGISTRY-}cuentaapi
    build:
      context: .
      dockerfile: CuentaAPI/Dockerfile

  clienteapi:
    image: ${DOCKER_REGISTRY-}clienteapi
    build:
      context: .
      dockerfile: ClienteAPI/Dockerfile

volumes:
  data_cuenta: 
  data_cliente:
    